### PR TITLE
strikedown the links where deadline has passed

### PR DESCRIPTION
**Pull request by kanak8278**
I will further check and update the deadline for other summer internship links.
This provides the students with a reminder of the deadline and saves time from visiting older links.

### CODE REVIEW

**Comment by Neptune2003** [comment]
The original owner of this repo is completely offline. He won't be there to approve your changes so its a waste of time. Do it in your fork. I will keep a lookout on it, as I'm currently applying too. Thank you for all your service :)

**Comment by himahuja** [comment]
I am here. :)

**Comment by himahuja** [comment]
The way I intended this repository to work was to have the links be updated every year for internships. So striking out internships would not do. If you want to contribute to the repository, you may convert the whole thing into a table, with country, internship title, link, and the closest approaching deadline. Let me know if you're interested and you would need more clarification of the intention.

I do overlook this repository still, and plan to keep doing it unless someone reaches out to co-manage it.

**Comment by Nandan-N** [comment]
@himahuja I would like to co-manage this repository. Can I get the write access?

**Comment by kanak8278** [comment]
@himahuja I, too, would like to co-manage. I can also organize the links.

**Pull request closed without merging**
